import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*<head>*/}
      
      {/* Add the meta tag for the viewport within the Head component */}
      {/*<meta name="viewport" content="initial-scale=1, width=device-width" />*/}
      {/*</head>*/}
      
        <body className={inter.className}>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  )
}
